# Meta information
title: Reimer Software
description: Open source development with love.
license: All rights reserved.
url: https://reimer.dev
company:
  name: Reimer Software
  adress:
    street: Große Märkerstraße 20
    zip: 06108
    city: Halle (Saale)
    country: Germany
  email: info@reimer.dev
  telephone: "+49 174 9273954"
  vat_id: DE315339671
author:
  name: Jan Heinrich Reimer
  adress:
    street: Große Märkerstraße 20
    zip: 06108
    city: Halle (Saale)
    country: Germany
  email: heinrich@reimer.dev
  telephone: "+49 174 9273954"
social:
  default:
    image: /res/images/social/social_facebook.png
    logo: /res/images/logos/logo_brand.png
  facebook:
    username: HeinrichReimer
    link: https://www.facebook.com/HeinrichReimer
    image: /res/images/social/social_facebook.png
  twitter:
    username: ReimerSoftware
    link: https://twitter.com/ReimerSoftware
    image: /res/images/social/social_twitter.png
  github:
    username: reimersoftware
    link: https://github.com/reimersoftware
  linkedin:
    link: https://www.linkedin.com/in/heinrich-reimer-680877120
  xing:
    link: https://www.xing.com/profile/Heinrich_Reimer3
  stackoverflow:
    link: https://stackoverflow.com/users/2037482/heinrich
webmaster_verifications:
  google: 5mySK6jpuoQ7RT2vFF-GKGFtb4FWZwxLZ4aBcLwvUdw
  bing: 3653BD8AC68D24520E97C345142CC6FA
host: uberspace
keywords:
  - Android
  - Mobile
  - Software
  - Development
  - Entwicklung
  - Web
  - Webdesign
  - Consulting
  - Gewerbe
  - Selbstständig
  - Self employed
  - Freelancer
  - Jan
  - Heinrich
  - Reimer
  - Apps
  - Libraries
  - Open-Source
  - GitHub
  - Websites
  - Java
  - CSS
  - Markdown
  - User Interface

# Collections of posts
collections:
  - apps
  - libraries
  - websites
  - services

# Removes files and folders from Jekyll build
exclude:
  - node_modules
  - bower.json
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor
  - .travis.yml

# Default values
defaults:
  - scope:
      path: ""
    values:
      layout: page
  - scope:
      path: 'bower_components/*'
    values:
      sitemap: false # Don't generate sitemap entries for Bower components.

# HTML compressor configurations
compress_html:
  clippings: [div, p, ul, td, h1, h2, h3, h4, h5, h6, hr]
  comments: ["<!-- ", " -->"]
  endings: [li, td]
  startings: [html, head, body]
  ignore:
    envs:
      development

# Check HTML output
html_proofer:
  assume_extension: true
  check_favicon: true
  check_opengraph: true
  check_html: true
  check_img_http: true
  disable_external: true
  enforce_https: true
  file_ignore:
    - /bower_components\/.*/
  validation:
    report_missing_names: true
  cache:
    timeframe: 2d

# Markdown parser
markdown: kramdown

# Jekyll plugins
plugins:
  # will be executed top to bottom
  - jemoji
  - jekyll-gist
  - jekyll-avatar
  - jekyll-mentions
  - jekyll-titles-from-headings
  - jekyll-redirect-from
  # - jekyll-paginate
  # - jekyll-feed # Enable again when a blog is included.
  - jekyll-last-modified-at
  - jekyll-sitemap
