name: Deploy website

on: 
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build website
      run: './build.sh'

  deploy:
    needs: build

    runs-on: ubuntu-latest

    steps:
    - name: Deploying via SSH
      uses: appleboy/ssh-action@v0.0.6
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: refresh-portfolio
